import { HorizontalBox } from "std-widgets.slint";
export component Icon inherits Rectangle {
    in property <image> src;
    in property <string> name;
    in property <color> colorize;
    in-out property <int> active;
    in property <int> index;
    callback click();
    Rectangle {
        height: 80%;
        width: 80%;
        // border-radius: 5px;
        // border-width: 1px;
        // background: rgba(1,1,1,0.5);
        Rectangle {
            width: 80%;
            height: 60%;
            border-radius: 5px;
            border-width: 1px;
            border-color: active == index ? colorize : #000;
            // background: rgba(1,1,1,0.1);
            TouchArea {
                mouse-cursor: MouseCursor.pointer;
                HorizontalLayout {
                    alignment: center;
                    Image {
                        source: src;
                        colorize: active == index ? colorize : #000;
                    }
                }

                clicked => {
                    click();
                }
            }
        }
    }
}
