export component Player inherits Rectangle {
    HorizontalLayout {
        height: 20%;
        cover := Rectangle {
            width: 10%;
            height: 10%;
            Image {
                width: 100px;
                height: 100px;
                source: @image-url("https://i2.hdslb.com/bfs/archive/ca6ddd4f1c89af8133cae0fe38cd72c2d54f8e17.jpg");
            }
        }

        playerBar := Rectangle { }

        playerOptions := Rectangle { }
    }
}
