import { VerticalBox } from "std-widgets.slint";
export component Player inherits Rectangle {
    in property <image> image;
    HorizontalLayout {
        height: 100%;
        cover := Rectangle {
            width: 14%;
            background: black;
            VerticalLayout {
                height: 100%;
                Image {
                    height: 100%;
                    source: @image-url("../assets/cover2.png");
                    image-fit: fill;
                }
            }
        }

        playerBar := Rectangle { }

        playerOptions := Rectangle { }
    }
}
