import { Player } from "../components/Player.slint";
import { LineEdit, TextEdit } from "std-widgets.slint";
import { SInput } from "../modules/surrealism-ui/src/input/index.slint";
import { SIcon } from "../modules/surrealism-ui/src/icon/index.slint";
import { SText } from "../modules/surrealism-ui/src/text/index.slint";
import { Icon } from "../components/Icon.slint";
export component BaseView inherits Rectangle {
    callback search(string);
    background: red;
    height: 100%;
    width: 100%;
    callback moved();
    VerticalLayout {
        header := Rectangle {
            height: 10%;
            width: 100%;
            background: #fff;
            // background: green;
            TouchArea {
                height: 100%;
                width: 100%;
                input-wrapper := Rectangle {
                    width: 100%;
                    height: 100%;
                    border-color: black;
                    border-width: 1px;
                    HorizontalLayout {
                        width: 100%;
                        height: 100%;
                        alignment: start;
                        VerticalLayout {
                            alignment: center;
                            input := SInput {
                                x: 50px;
                                theme: Info;
                                width: 30%;
                                height: 50%;
                                accepted => {
                                    search(input.text)
                                }
                            }
                        }
                    }
                }

                moved => {
                    root.moved();
                    search("input.text")
                }
            }
        }

        container := Rectangle {
            height: 80%;
            @children
        }

        player := Player {
            background: #FFF;
        }
    }
}
