import { Player } from "../components/Player.slint";
export component BaseView inherits Rectangle {
    background: red;
    height: 100%;
    width: 100%;
    callback moved(length, length);
    TouchArea {
        VerticalLayout {
            header := Rectangle {
                height: 10%;
                background: green;
            }

            container := Rectangle {
                height: 80%;
                @children
            }

            player := Player {
                background: #FFF;
            }
        }

        moved => {
            root.moved(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
        }
    }
}
